### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'crs'


### ISSUE THREAD

**Issue by lindauju** [pedrocamargo/rasterstats#8]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterstats\rasterstats_dialogs.py", line 104, in run_stats
    histogram,
  File "C:/Users/lindauju/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterstats\run_raster_statistics.py", line 50, in __init__
    int(self.polygon_layer.crs().authid().split(":")[1])
AttributeError: 'NoneType' object has no attribute 'crs'

```
rasterstats 0.4.3, QGIS 3.10.5-A Coruña on Windows 10

**Comment by pedrocamargo** [comment]
Hi @lindauju ,  what are the steps to reproduce it?
